services:
  - type: web
    name: inhalink-backend
    runtime: java
    buildCommand: ./gradlew bootJar -x test
    startCommand: java -jar build/libs/inhalink-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        sync: false
